[2023-06-05 14:19:13,384] {processor.py:153} INFO - Started process (PID=183) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:19:13,395] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:19:13,396] {logging_mixin.py:115} INFO - [2023-06-05 14:19:13,396] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:19:13,428] {logging_mixin.py:115} INFO - [2023-06-05 14:19:13,427] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 11
    global df_gab_abstr = spark.read.parquet("hdfs://namenode:9000/DataLake/gab_abstr.parquet")
                        ^
SyntaxError: invalid syntax
[2023-06-05 14:19:13,430] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:19:17,450] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 4.072 seconds
[2023-06-05 14:19:59,567] {processor.py:153} INFO - Started process (PID=198) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:19:59,641] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:19:59,672] {logging_mixin.py:115} INFO - [2023-06-05 14:19:59,672] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:19:59,926] {logging_mixin.py:115} INFO - [2023-06-05 14:19:59,925] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 11
    global df_gab_abstr = spark.read.parquet("hdfs://namenode:9000/DataLake/gab_abstr.parquet")
                        ^
SyntaxError: invalid syntax
[2023-06-05 14:19:59,939] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:20:00,162] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.612 seconds
[2023-06-05 14:20:30,966] {processor.py:153} INFO - Started process (PID=214) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:20:30,975] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:20:30,977] {logging_mixin.py:115} INFO - [2023-06-05 14:20:30,977] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:20:31,060] {logging_mixin.py:115} INFO - [2023-06-05 14:20:31,059] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 11
    global df_gab_abstr = spark.read.parquet("hdfs://namenode:9000/DataLake/gab_abstr.parquet")
                        ^
SyntaxError: invalid syntax
[2023-06-05 14:20:31,077] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:20:31,134] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.173 seconds
[2023-06-05 14:21:01,881] {processor.py:153} INFO - Started process (PID=229) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:21:01,920] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:21:01,965] {logging_mixin.py:115} INFO - [2023-06-05 14:21:01,965] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:21:02,076] {logging_mixin.py:115} INFO - [2023-06-05 14:21:02,075] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 11
    global df_gab_abstr = spark.read.parquet("hdfs://namenode:9000/DataLake/gab_abstr.parquet")
                        ^
SyntaxError: invalid syntax
[2023-06-05 14:21:02,077] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:21:03,096] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 1.226 seconds
[2023-06-05 14:21:36,088] {processor.py:153} INFO - Started process (PID=244) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:21:36,090] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:21:36,091] {logging_mixin.py:115} INFO - [2023-06-05 14:21:36,091] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:21:36,107] {logging_mixin.py:115} INFO - [2023-06-05 14:21:36,106] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 11
    global df_gab_abstr = spark.read.parquet("hdfs://namenode:9000/DataLake/gab_abstr.parquet")
                        ^
SyntaxError: invalid syntax
[2023-06-05 14:21:36,108] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:21:36,496] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.413 seconds
[2023-06-05 14:22:09,281] {processor.py:153} INFO - Started process (PID=259) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:22:09,315] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:22:09,318] {logging_mixin.py:115} INFO - [2023-06-05 14:22:09,317] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:22:09,368] {logging_mixin.py:115} INFO - [2023-06-05 14:22:09,367] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 11
    global df_gab_abstr = spark.read.parquet("hdfs://namenode:9000/DataLake/gab_abstr.parquet")
                        ^
SyntaxError: invalid syntax
[2023-06-05 14:22:09,370] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:22:09,573] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.300 seconds
[2023-06-05 14:22:40,783] {processor.py:153} INFO - Started process (PID=274) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:22:40,785] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:22:40,786] {logging_mixin.py:115} INFO - [2023-06-05 14:22:40,786] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:22:40,879] {logging_mixin.py:115} INFO - [2023-06-05 14:22:40,877] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 11
    global df_gab_abstr = spark.read.parquet("hdfs://namenode:9000/DataLake/gab_abstr.parquet")
                        ^
SyntaxError: invalid syntax
[2023-06-05 14:22:40,880] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:22:41,395] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.616 seconds
[2023-06-05 14:23:27,273] {processor.py:153} INFO - Started process (PID=284) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:23:27,290] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:23:27,323] {logging_mixin.py:115} INFO - [2023-06-05 14:23:27,323] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:23:27,666] {logging_mixin.py:115} INFO - [2023-06-05 14:23:27,662] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 24
    global df_solde = spark.read.parquet("hdfs://namenode:9000/DataLake/solde.parquet")
                    ^
SyntaxError: invalid syntax
[2023-06-05 14:23:27,670] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:23:27,773] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.510 seconds
[2023-06-05 14:23:58,386] {processor.py:153} INFO - Started process (PID=299) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:23:58,389] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:23:58,393] {logging_mixin.py:115} INFO - [2023-06-05 14:23:58,392] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:24:03,031] {logging_mixin.py:115} INFO - [2023-06-05 14:23:58,466] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 24
    global df_solde = spark.read.parquet("hdfs://namenode:9000/DataLake/solde.parquet")
                    ^
SyntaxError: invalid syntax
[2023-06-05 14:24:03,037] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:24:03,375] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 5.000 seconds
[2023-06-05 14:24:04,143] {processor.py:153} INFO - Started process (PID=314) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:24:04,144] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:24:04,146] {logging_mixin.py:115} INFO - [2023-06-05 14:24:04,145] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:24:04,630] {logging_mixin.py:115} INFO - [2023-06-05 14:24:04,625] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:24:04,634] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:24:10,000] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 5.877 seconds
[2023-06-05 14:24:22,219] {processor.py:153} INFO - Started process (PID=319) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:24:22,221] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:24:22,231] {logging_mixin.py:115} INFO - [2023-06-05 14:24:22,231] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:24:22,368] {logging_mixin.py:115} INFO - [2023-06-05 14:24:22,342] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:24:22,373] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:24:22,495] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.294 seconds
[2023-06-05 14:24:22,955] {processor.py:153} INFO - Started process (PID=330) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:24:22,958] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:24:22,960] {logging_mixin.py:115} INFO - [2023-06-05 14:24:22,959] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:24:23,032] {logging_mixin.py:115} INFO - [2023-06-05 14:24:23,023] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:24:23,041] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:24:23,110] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.167 seconds
[2023-06-05 14:24:53,749] {processor.py:153} INFO - Started process (PID=344) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:24:53,751] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:24:53,761] {logging_mixin.py:115} INFO - [2023-06-05 14:24:53,753] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:24:54,328] {logging_mixin.py:115} INFO - [2023-06-05 14:24:53,871] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:24:54,329] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:24:55,473] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 1.744 seconds
[2023-06-05 14:25:54,813] {processor.py:153} INFO - Started process (PID=355) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:25:54,840] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:25:54,842] {logging_mixin.py:115} INFO - [2023-06-05 14:25:54,842] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:25:55,093] {logging_mixin.py:115} INFO - [2023-06-05 14:25:55,076] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:25:55,097] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:25:55,180] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.386 seconds
[2023-06-05 14:26:26,095] {processor.py:153} INFO - Started process (PID=370) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:26:26,096] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:26:26,103] {logging_mixin.py:115} INFO - [2023-06-05 14:26:26,102] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:26:26,209] {logging_mixin.py:115} INFO - [2023-06-05 14:26:26,203] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:26:26,212] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:26:26,298] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.224 seconds
[2023-06-05 14:26:56,623] {processor.py:153} INFO - Started process (PID=385) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:26:56,624] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:26:56,625] {logging_mixin.py:115} INFO - [2023-06-05 14:26:56,625] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:26:56,647] {logging_mixin.py:115} INFO - [2023-06-05 14:26:56,641] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:26:56,649] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:26:56,683] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.065 seconds
[2023-06-05 14:27:27,215] {processor.py:153} INFO - Started process (PID=400) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:27:27,227] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:27:27,228] {logging_mixin.py:115} INFO - [2023-06-05 14:27:27,228] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:27:27,288] {logging_mixin.py:115} INFO - [2023-06-05 14:27:27,283] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:27:27,290] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:27:28,156] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.947 seconds
[2023-06-05 14:28:36,418] {processor.py:153} INFO - Started process (PID=415) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:28:39,246] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:28:39,563] {logging_mixin.py:115} INFO - [2023-06-05 14:28:39,563] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:28:42,231] {logging_mixin.py:115} INFO - [2023-06-05 14:28:42,225] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:28:42,234] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:28:43,363] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 6.951 seconds
[2023-06-05 14:29:18,643] {processor.py:153} INFO - Started process (PID=430) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:29:18,670] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:29:18,673] {logging_mixin.py:115} INFO - [2023-06-05 14:29:18,673] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:29:18,784] {logging_mixin.py:115} INFO - [2023-06-05 14:29:18,779] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:29:18,786] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:29:18,949] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.312 seconds
[2023-06-05 14:29:58,429] {processor.py:153} INFO - Started process (PID=444) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:29:58,438] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:29:58,450] {logging_mixin.py:115} INFO - [2023-06-05 14:29:58,450] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:30:00,073] {logging_mixin.py:115} INFO - [2023-06-05 14:30:00,067] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:30:00,076] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:30:09,245] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 10.820 seconds
[2023-06-05 14:31:15,754] {processor.py:153} INFO - Started process (PID=452) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:31:18,110] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:31:18,127] {logging_mixin.py:115} INFO - [2023-06-05 14:31:18,126] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:31:18,303] {logging_mixin.py:115} INFO - [2023-06-05 14:31:18,282] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:31:18,306] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:31:18,883] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 13.496 seconds
[2023-06-05 14:32:28,266] {processor.py:153} INFO - Started process (PID=466) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:32:28,310] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:32:28,312] {logging_mixin.py:115} INFO - [2023-06-05 14:32:28,312] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:32:30,400] {logging_mixin.py:115} INFO - [2023-06-05 14:32:29,904] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:32:30,496] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:32:31,923] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 31.619 seconds
[2023-06-05 14:36:01,233] {processor.py:153} INFO - Started process (PID=488) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:36:24,365] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:36:24,421] {logging_mixin.py:115} INFO - [2023-06-05 14:36:24,417] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:36:43,245] {logging_mixin.py:115} INFO - [2023-06-05 14:36:43,244] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1
    !pip install pyspark
    ^
SyntaxError: invalid syntax
[2023-06-05 14:36:43,246] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:36:44,095] {processor.py:153} INFO - Started process (PID=494) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:36:44,130] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:36:44,161] {logging_mixin.py:115} INFO - [2023-06-05 14:36:44,161] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:36:44,853] {logging_mixin.py:115} INFO - [2023-06-05 14:36:44,851] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1
    !pip install pyspark
    ^
SyntaxError: invalid syntax
[2023-06-05 14:36:44,856] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:36:44,969] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 1.033 seconds
[2023-06-05 14:37:15,428] {processor.py:153} INFO - Started process (PID=506) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:37:15,430] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:37:15,433] {logging_mixin.py:115} INFO - [2023-06-05 14:37:15,432] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:37:15,479] {logging_mixin.py:115} INFO - [2023-06-05 14:37:15,477] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1
    !pip install pyspark
    ^
SyntaxError: invalid syntax
[2023-06-05 14:37:15,480] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:37:15,526] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.103 seconds
[2023-06-05 14:37:49,481] {processor.py:153} INFO - Started process (PID=521) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:37:49,568] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:37:49,598] {logging_mixin.py:115} INFO - [2023-06-05 14:37:49,598] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:37:49,700] {logging_mixin.py:115} INFO - [2023-06-05 14:37:49,699] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1
    !pip install pyspark
    ^
SyntaxError: invalid syntax
[2023-06-05 14:37:49,701] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:37:50,062] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.609 seconds
[2023-06-05 14:38:06,413] {processor.py:153} INFO - Started process (PID=533) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:38:06,415] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:38:06,416] {logging_mixin.py:115} INFO - [2023-06-05 14:38:06,416] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:38:06,627] {logging_mixin.py:115} INFO - [2023-06-05 14:38:06,579] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:38:06,847] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:38:06,951] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.553 seconds
[2023-06-05 14:38:37,421] {processor.py:153} INFO - Started process (PID=548) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:38:37,430] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:38:37,435] {logging_mixin.py:115} INFO - [2023-06-05 14:38:37,435] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:38:37,493] {logging_mixin.py:115} INFO - [2023-06-05 14:38:37,486] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:38:37,494] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:38:37,541] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.125 seconds
[2023-06-05 14:39:07,680] {processor.py:153} INFO - Started process (PID=563) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:39:07,683] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:39:07,685] {logging_mixin.py:115} INFO - [2023-06-05 14:39:07,685] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:39:07,716] {logging_mixin.py:115} INFO - [2023-06-05 14:39:07,712] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:39:07,718] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:39:11,750] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 4.077 seconds
[2023-06-05 14:39:56,754] {processor.py:153} INFO - Started process (PID=581) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:39:56,755] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:39:56,757] {logging_mixin.py:115} INFO - [2023-06-05 14:39:56,757] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:39:56,788] {logging_mixin.py:115} INFO - [2023-06-05 14:39:56,783] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:39:56,789] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:39:56,843] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.096 seconds
[2023-06-05 14:40:56,000] {processor.py:153} INFO - Started process (PID=601) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:40:56,002] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:40:56,013] {logging_mixin.py:115} INFO - [2023-06-05 14:40:56,013] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:40:56,233] {logging_mixin.py:115} INFO - [2023-06-05 14:40:56,207] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:40:56,237] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:40:56,327] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.344 seconds
[2023-06-05 14:41:28,848] {processor.py:153} INFO - Started process (PID=623) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:41:28,849] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:41:28,850] {logging_mixin.py:115} INFO - [2023-06-05 14:41:28,850] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:41:28,868] {logging_mixin.py:115} INFO - [2023-06-05 14:41:28,865] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:41:28,870] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:41:28,943] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.100 seconds
[2023-06-05 14:44:23,164] {processor.py:153} INFO - Started process (PID=664) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:44:23,167] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:44:23,168] {logging_mixin.py:115} INFO - [2023-06-05 14:44:23,168] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:44:23,210] {logging_mixin.py:115} INFO - [2023-06-05 14:44:23,205] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:44:23,212] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:44:23,424] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.264 seconds
[2023-06-05 14:44:56,301] {processor.py:153} INFO - Started process (PID=682) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:44:56,303] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:44:56,306] {logging_mixin.py:115} INFO - [2023-06-05 14:44:56,305] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:44:56,358] {logging_mixin.py:115} INFO - [2023-06-05 14:44:56,350] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:44:56,361] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:44:56,435] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.143 seconds
[2023-06-05 14:45:26,774] {processor.py:153} INFO - Started process (PID=702) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:45:26,791] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:45:26,793] {logging_mixin.py:115} INFO - [2023-06-05 14:45:26,792] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:45:26,883] {logging_mixin.py:115} INFO - [2023-06-05 14:45:26,878] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:45:26,885] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:45:26,952] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.184 seconds
[2023-06-05 14:45:57,548] {processor.py:153} INFO - Started process (PID=724) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:45:57,552] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:45:57,555] {logging_mixin.py:115} INFO - [2023-06-05 14:45:57,555] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:45:57,610] {logging_mixin.py:115} INFO - [2023-06-05 14:45:57,605] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:45:57,612] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:45:57,702] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.160 seconds
[2023-06-05 14:46:28,001] {processor.py:153} INFO - Started process (PID=742) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:46:28,003] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:46:28,005] {logging_mixin.py:115} INFO - [2023-06-05 14:46:28,005] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:46:28,069] {logging_mixin.py:115} INFO - [2023-06-05 14:46:28,028] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:46:28,071] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:46:29,925] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 1.936 seconds
[2023-06-05 14:47:04,046] {processor.py:153} INFO - Started process (PID=762) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:47:04,103] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:47:04,130] {logging_mixin.py:115} INFO - [2023-06-05 14:47:04,130] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:47:05,063] {logging_mixin.py:115} INFO - [2023-06-05 14:47:04,842] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:47:05,126] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:55:53,031] {processor.py:153} INFO - Started process (PID=198) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:55:53,138] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:55:53,175] {logging_mixin.py:115} INFO - [2023-06-05 14:55:53,175] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:55:54,285] {logging_mixin.py:115} INFO - [2023-06-05 14:55:54,152] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:55:54,324] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:55:54,403] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 1.378 seconds
[2023-06-05 14:56:33,312] {processor.py:153} INFO - Started process (PID=216) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:56:33,336] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:56:33,424] {logging_mixin.py:115} INFO - [2023-06-05 14:56:33,424] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:56:34,685] {logging_mixin.py:115} INFO - [2023-06-05 14:56:34,677] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:56:34,688] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:56:34,870] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 1.563 seconds
[2023-06-05 14:57:05,162] {processor.py:153} INFO - Started process (PID=236) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:57:05,166] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:57:05,194] {logging_mixin.py:115} INFO - [2023-06-05 14:57:05,194] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:57:08,374] {logging_mixin.py:115} INFO - [2023-06-05 14:57:07,560] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:57:08,483] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:57:08,727] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 3.543 seconds
[2023-06-05 14:57:39,164] {processor.py:153} INFO - Started process (PID=258) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:57:39,165] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:57:39,167] {logging_mixin.py:115} INFO - [2023-06-05 14:57:39,166] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:57:39,195] {logging_mixin.py:115} INFO - [2023-06-05 14:57:39,189] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:57:39,197] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:57:39,258] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.100 seconds
[2023-06-05 14:58:09,547] {processor.py:153} INFO - Started process (PID=278) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:58:09,547] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:58:09,548] {logging_mixin.py:115} INFO - [2023-06-05 14:58:09,548] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:58:09,565] {logging_mixin.py:115} INFO - [2023-06-05 14:58:09,562] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:58:09,566] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:58:09,726] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.182 seconds
[2023-06-05 14:58:40,294] {processor.py:153} INFO - Started process (PID=298) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:58:40,295] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:58:40,296] {logging_mixin.py:115} INFO - [2023-06-05 14:58:40,295] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:58:40,347] {logging_mixin.py:115} INFO - [2023-06-05 14:58:40,342] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:58:40,350] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:58:40,513] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.224 seconds
[2023-06-05 14:59:10,701] {processor.py:153} INFO - Started process (PID=318) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:59:10,732] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:59:10,737] {logging_mixin.py:115} INFO - [2023-06-05 14:59:10,737] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:59:10,819] {logging_mixin.py:115} INFO - [2023-06-05 14:59:10,813] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:59:10,821] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:59:10,995] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.298 seconds
[2023-06-05 14:59:41,067] {processor.py:153} INFO - Started process (PID=338) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 14:59:41,079] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 14:59:41,080] {logging_mixin.py:115} INFO - [2023-06-05 14:59:41,080] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:59:41,148] {logging_mixin.py:115} INFO - [2023-06-05 14:59:41,144] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 14:59:41,149] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 14:59:41,302] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.240 seconds
[2023-06-05 15:00:11,613] {processor.py:153} INFO - Started process (PID=358) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 15:00:11,615] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 15:00:11,616] {logging_mixin.py:115} INFO - [2023-06-05 15:00:11,616] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 15:00:11,678] {logging_mixin.py:115} INFO - [2023-06-05 15:00:11,672] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 15:00:11,686] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 15:00:11,752] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.143 seconds
[2023-06-05 15:06:22,046] {processor.py:153} INFO - Started process (PID=397) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 15:06:22,050] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 15:06:22,051] {logging_mixin.py:115} INFO - [2023-06-05 15:06:22,051] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 15:06:22,319] {logging_mixin.py:115} INFO - [2023-06-05 15:06:22,300] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 15:06:22,320] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 15:06:31,608] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 9.569 seconds
[2023-06-05 15:07:40,400] {processor.py:153} INFO - Started process (PID=420) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 15:07:40,401] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 15:07:40,403] {logging_mixin.py:115} INFO - [2023-06-05 15:07:40,402] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 15:07:40,440] {logging_mixin.py:115} INFO - [2023-06-05 15:07:40,435] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 15:07:40,442] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 15:07:40,759] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.364 seconds
[2023-06-05 15:08:19,771] {processor.py:153} INFO - Started process (PID=442) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 15:08:19,802] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 15:08:19,804] {logging_mixin.py:115} INFO - [2023-06-05 15:08:19,804] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 15:08:20,213] {logging_mixin.py:115} INFO - [2023-06-05 15:08:20,208] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 15:08:20,216] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 15:08:20,706] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.942 seconds
[2023-06-05 15:08:51,145] {processor.py:153} INFO - Started process (PID=460) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 15:08:51,154] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 15:08:51,156] {logging_mixin.py:115} INFO - [2023-06-05 15:08:51,156] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 15:08:51,393] {logging_mixin.py:115} INFO - [2023-06-05 15:08:51,381] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 15:08:51,400] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 15:08:51,614] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.475 seconds
[2023-06-05 15:09:22,808] {processor.py:153} INFO - Started process (PID=482) to work on /opt/airflow/dags/Load_Data.py
[2023-06-05 15:09:22,812] {processor.py:641} INFO - Processing file /opt/airflow/dags/Load_Data.py for tasks to queue
[2023-06-05 15:09:22,816] {logging_mixin.py:115} INFO - [2023-06-05 15:09:22,816] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/Load_Data.py
[2023-06-05 15:09:22,864] {logging_mixin.py:115} INFO - [2023-06-05 15:09:22,856] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/Load_Data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Load_Data.py", line 1, in <module>
    from pyspark.sql.functions import when, col, date_format
ModuleNotFoundError: No module named 'pyspark'
[2023-06-05 15:09:22,866] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Load_Data.py
[2023-06-05 15:09:22,928] {processor.py:161} INFO - Processing /opt/airflow/dags/Load_Data.py took 0.125 seconds
